### ISSUE TITLE
Error: `panic: runtime error: invalid memory address or nil pointer dereference` When using JSON output

### ISSUE THREAD

**Issue by Nishantbhagat57** [sw33tLie/uff#3]
## Command
`uff -t 20 -fc 404 -v -timeout 30 -w /home/nishant57/test/wordlist.txt -u "https://xyz.mainapp.com/FUZZ" -o xyz.mainapp.json -od xyzmainapp -of json`

## Output
```
:: Progress: [2/44] :: Job [1/1] :: 0 req/sec :: Duration: [0:00:00] :: Errors: 0 ::panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x714e52]

goroutine 6 [running]:
github.com/sw33tLie/oohttp.readRequest(0xc000118420)
	/home/nishant57/go/pkg/mod/github.com/sw33t!lie/oohttp@v0.0.0-20240612152135-5aeb3b3d6240/request.go:1107 +0x3d2
github.com/sw33tLie/oohttp.ReadRequest(0x0?)
	/home/nishant57/go/pkg/mod/github.com/sw33t!lie/oohttp@v0.0.0-20240612152135-5aeb3b3d6240/request.go:1027 +0x13
github.com/sw33tLie/oohttp/httputil.DumpRequestOut.func2()
	/home/nishant57/go/pkg/mod/github.com/sw33t!lie/oohttp@v0.0.0-20240612152135-5aeb3b3d6240/httputil/dump.go:133 +0x145
created by github.com/sw33tLie/oohttp/httputil.DumpRequestOut in goroutine 5
	/home/nishant57/go/pkg/mod/github.com/sw33t!lie/oohttp@v0.0.0-20240612152135-5aeb3b3d6240/httputil/dump.go:132 +0x619
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x714e52]

goroutine 21 [running]:
github.com/sw33tLie/oohttp.readRequest(0xc000118300)
	/home/nishant57/go/pkg/mod/github.com/sw33t!lie/oohttp@v0.0.0-20240612152135-5aeb3b3d6240/request.go:1107 +0x3d2
github.com/sw33tLie/oohttp.ReadRequest(0x0?)
	/home/nishant57/go/pkg/mod/github.com/sw33t!lie/oohttp@v0.0.0-20240612152135-5aeb3b3d6240/request.go:1027 +0x13
github.com/sw33tLie/oohttp/httputil.DumpRequestOut.func2()
	/home/nishant57/go/pkg/mod/github.com/sw33t!lie/oohttp@v0.0.0-20240612152135-5aeb3b3d6240/httputil/dump.go:133 +0x145
created by github.com/sw33tLie/oohttp/httputil.DumpRequestOut in goroutine 20
	/home/nishant57/go/pkg/mod/github.com/sw33t!lie/oohttp@v0.0.0-20240612152135-5aeb3b3d6240/httputil/dump.go:132 +0x619

```

The command works perfectly with original FFUF

**Comment by sw33tLie** [comment]
Fixed! :)
